// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaD5bhviIFqmNNZfMvD0qbym4E3Ox-K84',
    appId: '1:368665369493:web:9d47accd4bc7e217b9749c',
    messagingSenderId: '368665369493',
    projectId: 'sparkhub-app-database',
    authDomain: 'sparkhub-app-database.firebaseapp.com',
    databaseURL: 'https://sparkhub-app-database-default-rtdb.firebaseio.com',
    storageBucket: 'sparkhub-app-database.appspot.com',
    measurementId: 'G-WJ6N1ZV93T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmhqe_Ws7d4Pbf_q18G9uUr1ivo_tkng',
    appId: '1:368665369493:android:93a866495644b19fb9749c',
    messagingSenderId: '368665369493',
    projectId: 'sparkhub-app-database',
    databaseURL: 'https://sparkhub-app-database-default-rtdb.firebaseio.com',
    storageBucket: 'sparkhub-app-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7tTd_16dHTJoJjed6fHqHU5ogVrIw6J8',
    appId: '1:368665369493:ios:837de3574d66be7eb9749c',
    messagingSenderId: '368665369493',
    projectId: 'sparkhub-app-database',
    databaseURL: 'https://sparkhub-app-database-default-rtdb.firebaseio.com',
    storageBucket: 'sparkhub-app-database.appspot.com',
    iosClientId: '368665369493-9n18urnnd51dt42s5vgpr3ndtkun2eim.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkhubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7tTd_16dHTJoJjed6fHqHU5ogVrIw6J8',
    appId: '1:368665369493:ios:837de3574d66be7eb9749c',
    messagingSenderId: '368665369493',
    projectId: 'sparkhub-app-database',
    databaseURL: 'https://sparkhub-app-database-default-rtdb.firebaseio.com',
    storageBucket: 'sparkhub-app-database.appspot.com',
    iosClientId: '368665369493-9n18urnnd51dt42s5vgpr3ndtkun2eim.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkhubApp',
  );
}
